---
name: PR Lint

permissions: {}

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    branches: [master, main]

jobs:
  LintPush:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
    steps:
      - uses: ivuorinen/actions/pr-lint@de31e11dda6488eabe95e951ebb61c6d9d500865 # v2026.06.30

  LintPR:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write
      issues: write
      pull-requests: write
    steps:
      - uses: ivuorinen/actions/pr-lint@de31e11dda6488eabe95e951ebb61c6d9d500865 # v2026.06.30
