---
name: PR Lint

permissions: {}

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    branches: [master, main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  LintPush:
    name: Lint on push
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write # post commit status for lint result
    steps:
      - uses: ivuorinen/actions/pr-lint@de31e11dda6488eabe95e951ebb61c6d9d500865 # v2026.06.30

  LintPR:
    name: Lint on pull request
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write # post commit status for lint result
      issues: write # add label/comment on lint failure
      pull-requests: write # add review comment on lint failure
    steps:
      - uses: ivuorinen/actions/pr-lint@de31e11dda6488eabe95e951ebb61c6d9d500865 # v2026.06.30
