---
name: Stale

permissions: {}

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "0 8 * * *"
  workflow_call:
  workflow_dispatch:

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
    steps:
      - uses: ivuorinen/actions/stale@877acc6d8b013051a6acf83c0e876d3a2b46210a # v2026.06.08
